name: Release
on:
  workflow_dispatch:

jobs:
  build:
    name: Manual Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" > .npmrc
      - run: cat .npmrc
